# Generated by Django 6.0.4 on 2026-05-04 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(choices=[('conservative', 'Conservative'), ('balanced', 'Balanced'), ('aggressive', 'Aggressive')], max_length=16)),
                ('monthly_longevity_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterventionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('supplement', 'Supplement'), ('prevention', 'Prevention'), ('diagnostic', 'Diagnostic'), ('fitness', 'Fitness')], max_length=32)),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('trust_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('available_in_region', models.CharField(blank=True, default='Germany', max_length=128)),
                ('insurance_hint', models.CharField(blank=True, default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('country', models.CharField(default='Germany', max_length=64)),
                ('region', models.CharField(max_length=128)),
                ('insurance_type', models.CharField(choices=[('GKV', 'GKV'), ('PKV', 'PKV')], default='GKV', max_length=3)),
                ('risk_preference', models.CharField(default='balanced', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=32)),
                ('monthly_allocation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rationale', models.TextField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='planner.budgetplan')),
                ('intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.interventionoption')),
            ],
        ),
        migrations.CreateModel(
            name='LongevityGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='planner.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fixed_costs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discretionary_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('emergency_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='planner.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='budgetplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='planner.userprofile'),
        ),
    ]
