# Generated by Django 6.0.4 on 2026-05-05 00:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionoption',
            name='bioavailability_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.0'), help_text='Expected absorption / formulation quality (0–10).', max_digits=4),
        ),
        migrations.AddField(
            model_name='interventionoption',
            name='purity_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.0'), help_text='Label purity / third-party testing rigor (0–10).', max_digits=4),
        ),
    ]
