# Generated by Django 6.0.6 on 2026-06-05 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('aliases', models.JSONField(default=list, help_text="Alternate search terms, e.g. ['solo io', 'get solo']")),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QualityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('weight', models.FloatField(default=1.0, help_text='Weight when computing overall TrustScore (0–10).')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'quality categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='olive_oil', help_text='Product type for grouping comparisons.', max_length=64)),
                ('label_claims', models.JSONField(default=dict, help_text="Declared values from label, e.g. {'polyphenols_mg_kg': 500}")),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='coa.brand')),
            ],
            options={
                'ordering': ['brand__name', 'name'],
                'unique_together': {('brand', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CertificateOfAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=128)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('lab_name', models.CharField(blank=True, max_length=255)),
                ('lab_type', models.CharField(choices=[('third_party', 'Third-party ISO 17025'), ('in_house_iso', 'In-house ISO 17025'), ('in_house', 'In-house (non-accredited)'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('is_public', models.BooleanField(default=False, help_text="Consumer can look up this lot's COA online.")),
                ('document_url', models.URLField(blank=True, max_length=500)),
                ('is_primary', models.BooleanField(default=False, help_text='Preferred COA used for TrustScore when multiple exist.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coas', to='coa.product')),
            ],
            options={
                'verbose_name': 'certificate of analysis',
                'verbose_name_plural': 'certificates of analysis',
                'ordering': ['-test_date', '-id'],
                'unique_together': {('product', 'lot_number')},
            },
        ),
        migrations.CreateModel(
            name='CoaMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_key', models.CharField(help_text='Stable key, e.g. polyphenols_mg_kg, lead_ppb', max_length=64)),
                ('indicator_label', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('numeric', 'Numeric'), ('boolean', 'Boolean'), ('enum', 'Enum')], default='numeric', max_length=16)),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('enum_value', models.CharField(blank=True, max_length=64)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('label_claim', models.FloatField(blank=True, help_text='Declared label value for potency/accuracy checks.', null=True)),
                ('pass_threshold', models.FloatField(blank=True, help_text='Max allowed (contaminants) or min required (actives).', null=True)),
                ('notes', models.TextField(blank=True)),
                ('coa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='coa.certificateofanalysis')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='coa.qualitycategory')),
            ],
            options={
                'ordering': ['category__sort_order', 'indicator_label'],
                'unique_together': {('coa', 'indicator_key')},
            },
        ),
    ]
