# Generated by Django 6.0.5 on 2026-05-19 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('rf', 'RF / Wireless'), ('safety', 'Safety'), ('medical', 'Medical'), ('quality', 'Quality'), ('emc', 'EMC'), ('battery', 'Battery / Transport')], max_length=32)),
                ('unlocks', models.TextField(help_text='Marketing one-liner for what this unlocks')),
                ('official_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TestingLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('regions', models.JSONField(default=list)),
                ('accreditations', models.JSONField(default=list)),
                ('categories', models.JSONField(default=list)),
                ('contact_url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('analyzing', 'Analyzing'), ('ready', 'Ready'), ('in_lab', 'In lab'), ('cleared', 'Cleared')], default='draft', max_length=16)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('research', 'Research'), ('documentation', 'Documentation')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='compliance.complianceproject')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('product_category', models.CharField(default='consumer_iot', max_length=128)),
                ('target_markets', models.JSONField(default=list)),
                ('has_rf', models.BooleanField(default=False)),
                ('has_battery', models.BooleanField(default=False)),
                ('is_medical', models.BooleanField(default=False)),
                ('medical_class', models.CharField(blank=True, max_length=32)),
                ('intended_use', models.TextField(blank=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='compliance.complianceproject')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=16)),
                ('product_tags', models.JSONField(default=list, help_text='e.g. wifi, battery, wellness, medical_class_I')),
                ('markets', models.JSONField(default=list, help_text='e.g. US, EU, DE')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='compliance.standard')),
            ],
            options={
                'ordering': ['standard__code', 'clause_id'],
                'unique_together': {('standard', 'clause_id')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('research', 'Research'), ('documentation', 'Documentation'), ('lab', 'Lab'), ('clearance', 'Clearance')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='pending', max_length=16)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('blocker_note', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='compliance.complianceproject')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('HARA', 'Hazard Analysis'), ('technical_file', 'Technical file'), ('risk_management', 'Risk management'), ('labeling', 'Labeling')], max_length=32)),
                ('section', models.CharField(max_length=128)),
                ('content_md', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='compliance.complianceproject')),
            ],
            options={
                'ordering': ['doc_type', 'section'],
                'unique_together': {('project', 'doc_type', 'section')},
            },
        ),
        migrations.CreateModel(
            name='RequirementMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applicable', 'Applicable'), ('not_applicable', 'Not applicable'), ('needs_review', 'Needs review')], default='needs_review', max_length=20)),
                ('citation', models.CharField(blank=True, max_length=500)),
                ('rationale', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('reviewed', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='compliance.complianceproject')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='compliance.requirement')),
            ],
            options={
                'unique_together': {('project', 'requirement')},
            },
        ),
        migrations.CreateModel(
            name='LabMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('contacted', 'Contacted'), ('engaged', 'Engaged')], default='suggested', max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_matches', to='compliance.complianceproject')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='compliance.testinglab')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('project', 'lab')},
            },
        ),
    ]
